Repository chicken-sloths/bangazon-api-sprint1, pull requests merged in 2018-03, with the labels that each got.

#24 Creates pull_request_template.md
  .github/pull_request_template.md
Labels: init

#23 Creates issue_template.md
  .github/issue_template.md
Labels: init

#27 Fixes #21: initializes models
  models/employees/ComputersModel.js
  models/employees/DepartmentsModel.js
  models/employees/EmployeeComputersModel.js
  models/employees/EmployeeTrainingProgramsModel.js
  models/employees/EmployeesModel.js
  models/employees/TrainingProgramsModel.js
  models/products/CustomersModel.js
  models/products/OrdersModel.js
  models/products/PaymentOptionsModel.js
  models/products/ProductOrdersModel.js
  models/products/ProductTypesModel.js
  models/products/ProductsModel.js
Labels: init

#33 Build Data File
  data/build-data.js
Labels: init

#35 Fixes #13
  routes/employees/computers.js
  routes/employees/departments.js
  routes/employees/employeeComputers.js
  routes/employees/employeeTrainingPrograms.js
  routes/employees/employees.js
  routes/employees/trainingPrograms.js
  routes/index.js
  routes/products/customers.js
  routes/products/orders.js
  routes/products/paymentOptions.js
  routes/products/productOrders.js
  routes/products/productTypes.js
  routes/products/products.js
Labels: init

#28 Faker Product JSON Generator
  data/faker/exampleFakerController.js
  data/faker/products/_customersFaker.js
  data/faker/products/_ordersFaker.js
  data/faker/products/_paymentOptionsFaker.js
  data/faker/products/_productOrdersFaker.js
  data/faker/products/_productTypesFaker.js
  data/faker/products/_productsFaker.js
  data/faker/products/index.js
  data/faker/randomInt.js
Labels: init

#29 employee faker data #20
  data/build-data.js
  data/faker/employees/computerFaker.js
  data/faker/employees/departmentFaker.js
  data/faker/employees/employeeComputerFaker.js
  data/faker/employees/employeeFaker.js
  data/faker/employees/employeeTrainingProgramFaker.js
  data/faker/employees/index.js
  data/faker/employees/trainingProgramFaker.js
Labels: init

#62 build data
  data/build-data.js
  data/faker/employees/index.js
  data/faker/exampleFakerController.js
  data/faker/products/index.js
  data/json/computers.json
  data/json/customers.json
  data/json/departments.json
  data/json/employeeComputers.json
  data/json/employeeTrainingPrograms.json
  data/json/employees.json
  data/json/orders.json
  data/json/paymentOptions.json
  data/json/productOrders.json
  data/json/productTypes.json
  data/json/products.json
  data/json/trainingPrograms.json
Labels: init

#63 Refactor of filepaths, adds indexes for routes/ & fixes typos on routes/index.js
  controllers/employees/computersCtrl.js
  controllers/employees/departmentsCtrl.js
  controllers/employees/employeeComputersCtrl.js
  controllers/employees/employeeTrainingProgramsCtrl.js
  controllers/employees/employeesCtrl.js
  controllers/employees/trainingProgramsCtrl.js
  controllers/products/customersCtrl.js
  controllers/products/ordersCtrl.js
  controllers/products/paymentOptionsCtrl.js
  controllers/products/productOrderCtrl.js
  controllers/products/productTypesCtrl.js
  controllers/products/productsCtrl.js
  routes/employees/computers.js
  routes/employees/departments.js
  routes/employees/employeeComputers.js
  routes/employees/employeeTrainingPrograms.js
  routes/employees/employees.js
  routes/employees/index.js
  routes/employees/trainingPrograms.js
  routes/index.js
  routes/products/customers.js
  routes/products/index.js
  routes/products/orders.js
  routes/products/paymentOptions.js
  routes/products/productOrders.js
  routes/products/productTypes.js
  routes/products/products.js
Labels: init

#77 Fixes #42: Creates Product_Orders table
  db/products/makeProductOrderTable.js
Labels: pre-launch

#78 Create Product_Type Table.
  db/products/makeProductTypeTable.js
Labels: pre-launch

#80 Escape Single Quotes in Faker String
  db/sqlRunTemplate.js
Labels: bug

#71 Joe create and fill tables
  db/build-db.js
  db/employees/makeComputerTable.js
  db/employees/makeDepartmentTable.js
  db/employees/makeEmployeeComputerTable.js
  db/employees/makeEmployeeTable.js
  db/employees/makeEmployeeTrainingTable.js
  db/employees/makeTrainingProgramTable.js
  db/products/makeOrderTable.js
  db/products/makeProductOrderTable.js
  db/products/makeProductTypeTable.js
  db/products/makeProductsTable.js
Labels: pre-launch

#82 Fix escapeSingleQuote trying to escape undefined value
  db/sqlRunTemplate.js
Labels: bug

#73 Create Product Table
  db/products/makeProductsTable.js
Labels: pre-launch

#83 Fixes #53: makeEmployeeTrainingTable finished
  db/employees/makeEmployeeTrainingTable.js
Labels: pre-launch

#74 Faker fixes
  data/build-data.js
  data/faker/employees/computerFaker.js
  data/faker/employees/departmentFaker.js
  data/faker/employees/employeeComputerFaker.js
  data/faker/employees/employeeFaker.js
  data/faker/employees/employeeTrainingProgramFaker.js
  data/faker/employees/index.js
  data/faker/employees/trainingProgramFaker.js
  data/json/computers.json
  data/json/customers.json
  data/json/departments.json
  data/json/employeeComputers.json
  data/json/employeeTrainingPrograms.json
  data/json/employees.json
  data/json/orders.json
  data/json/paymentOptions.json
  data/json/productOrders.json
  data/json/productTypes.json
  data/json/products.json
  data/json/trainingPrograms.json
  db/employees/makeComputerTable.js
  db/employees/makeDepartmentTable.js
  db/employees/makeEmployeeTable.js
  db/employees/makeEmployeeTrainingTable.js
  db/employees/makeTrainingProgramTable.js
  db/products/makeOrderTable.js
  db/products/makeProductOrderTable.js
  package-lock.json
  package.json
Labels: bug, init

#87 getSingleProduct & getAllProducts
  controllers/products/productsCtrl.js
  models/products/ProductsModel.js
  routes/products/products.js
Labels: feature

#89 getAllEmployees & getSingleEmployee
  .gitignore
  controllers/employees/employeesCtrl.js
  models/employees/EmployeesModel.js
  routes/employees/employees.js
  routes/employees/index.js
Labels: pre-launch

#93 Updates package.json & app.js to use body-parser
  app.js
  package.json
Labels: pre-launch

#92 Fixes #64 Sets up routes and end points for the Customers
  controllers/products/customersCtrl.js
  models/products/CustomersModel.js
  routes/products/customers.js
Labels: feature

#95 all methods on /computers endpoints
  controllers/employees/computersCtrl.js
  models/employees/ComputersModel.js
  routes/employees/computers.js
Labels: feature

#99 put now works on nonexistent computer ids
  models/employees/ComputersModel.js
Labels: feature

#100 Fixes #6: GET, POST, PUT Employees
  controllers/employees/employeesCtrl.js
  models/employees/EmployeesModel.js
  routes/employees/employees.js
Labels: feature

#98 Departments POST and PUT
  controllers/employees/departmentsCtrl.js
  models/employees/DepartmentsModel.js
  routes/employees/departments.js
Labels: feature

#104 Fixes #5: GET, POST, PUT, & DELETE for Product_Types
  controllers/products/productTypesCtrl.js
  models/products/ProductTypesModel.js
  routes/products/index.js
  routes/products/productTypes.js
Labels: feature

#102 putProduct(), postProduct(), and deleteProduct()
  controllers/products/productsCtrl.js
  models/products/ProductsModel.js
  routes/products/products.js
Labels: feature

#105 `/training-programs` endpoints
  controllers/employees/trainingProgramsCtrl.js
  models/employees/TrainingProgramsModel.js
  routes/employees/index.js
  routes/employees/trainingPrograms.js
Labels: feature

#106 Orders Endpoints
  controllers/products/ordersCtrl.js
  models/employees/DepartmentsModel.js
  models/products/OrdersModel.js
  routes/products/orders.js
Labels: feature

#108 /payment-options endpoints
  controllers/products/paymentOptionsCtrl.js
  models/products/PaymentOptionsModel.js
  routes/products/index.js
  routes/products/paymentOptions.js
Labels: feature

#117 fixed routes so that the section prefix is in the index file of that …
  routes/employees/computers.js
  routes/employees/departments.js
  routes/employees/employees.js
  routes/employees/index.js
  routes/employees/trainingPrograms.js
  routes/products/customers.js
  routes/products/index.js
  routes/products/orders.js
  routes/products/paymentOptions.js
  routes/products/productTypes.js
  routes/products/products.js
Labels: refactor

#118 Tiny fix : handles errors with creating new orders
  controllers/products/ordersCtrl.js
  models/products/OrdersModel.js
Labels: refactor

#119 employees: combine put/post into update
  controllers/employees/employeesCtrl.js
  models/employees/EmployeesModel.js
  routes/employees/employees.js
Labels: refactor

#120 computers: combine put/post into update
  controllers/employees/computersCtrl.js
  models/employees/ComputersModel.js
  routes/employees/computers.js
Labels: refactor

#124 training programs: combine put/post into update
  controllers/employees/trainingProgramsCtrl.js
  models/employees/TrainingProgramsModel.js
  routes/employees/trainingPrograms.js
Labels: refactor

#123 payment options: combine put/post into update
  controllers/products/paymentOptionsCtrl.js
  models/products/PaymentOptionsModel.js
  routes/products/paymentOptions.js
Labels: refactor

#125 Fixes #86: Error handling & status codes
  app.js
  controllers/employees/computersCtrl.js
  controllers/employees/departmentsCtrl.js
  controllers/employees/employeesCtrl.js
  controllers/employees/trainingProgramsCtrl.js
  controllers/products/customersCtrl.js
  controllers/products/ordersCtrl.js
  controllers/products/paymentOptionsCtrl.js
  controllers/products/productTypesCtrl.js
  controllers/products/productsCtrl.js
  models/employees/ComputersModel.js
  models/employees/TrainingProgramsModel.js
  models/products/CustomersModel.js
  models/products/PaymentOptionsModel.js
Labels: pre-launch

#126 added a way to randomize payment types for our payment options
  data/faker/products/_paymentOptionsFaker.js
  data/json/paymentOptions.json
Labels: enhancement, refactor

#122 Cascading Orders Delete
  db/products/makeProductOrderTable.js
  models/products/OrdersModel.js
Labels: feature

#128 customers: put/post => update
  controllers/products/customersCtrl.js
  models/products/CustomersModel.js
  routes/products/customers.js
Labels: refactor

#130 Standardized File Names
  data/faker/employees/_computersFaker.js
  data/faker/employees/_departmentsFaker.js
  data/faker/employees/_employeeComputersFaker.js
  data/faker/employees/_employeeTrainingProgramsFaker.js
  data/faker/employees/_employeesFaker.js
  data/faker/employees/_trainingProgramsFaker.js
  data/faker/employees/index.js
  routes/employees/computersRouter.js
  routes/employees/departmentsRouter.js
  routes/employees/employeesRouter.js
  routes/employees/index.js
  routes/employees/trainingProgramsRouter.js
  routes/products/customersRouter.js
  routes/products/index.js
  routes/products/ordersRouter.js
  routes/products/paymentOptionsRouter.js
  routes/products/productTypesRouter.js
  routes/products/productsRouter.js
Labels: refactor

#131 products: post/put => update
  controllers/products/productsCtrl.js
  models/products/ProductsModel.js
  routes/products/productsRouter.js
Labels: refactor

#132 orders: put/post => update
  controllers/products/ordersCtrl.js
  models/products/OrdersModel.js
  routes/products/ordersRouter.js
Labels: refactor

#133 Readme update
  README.md
Labels: enhancement

#134 Fixes #107: this.changes on DELETE
  controllers/employees/computersCtrl.js
  controllers/employees/trainingProgramsCtrl.js
  controllers/products/ordersCtrl.js
  controllers/products/paymentOptionsCtrl.js
  controllers/products/productTypesCtrl.js
  controllers/products/productsCtrl.js
  models/employees/ComputersModel.js
  models/employees/TrainingProgramsModel.js
  models/products/OrdersModel.js
  models/products/PaymentOptionsModel.js
  models/products/ProductsModel.js
Labels: refactor

#136 Fixes #67: filepaths
  controllers/employees/departmentsCtrl.js
  controllers/employees/employeesCtrl.js
  controllers/products/customersCtrl.js
  controllers/products/ordersCtrl.js
  controllers/products/productTypesCtrl.js
  controllers/products/productsCtrl.js
  routes/employees/departmentsRouter.js
  routes/employees/employeesRouter.js
  routes/products/customersRouter.js
  routes/products/ordersRouter.js
  routes/products/paymentOptionsRouter.js
  routes/products/productTypesRouter.js
  routes/products/productsRouter.js
Labels: refactor

#137 Fixes #116
  controllers/employees/computersCtrl.js
  controllers/employees/employeesCtrl.js
  controllers/employees/trainingProgramsCtrl.js
  controllers/products/customersCtrl.js
  controllers/products/ordersCtrl.js
  controllers/products/paymentOptionsCtrl.js
  controllers/products/productsCtrl.js
  models/employees/ComputersModel.js
  models/employees/DepartmentsModel.js
  models/employees/EmployeesModel.js
  models/employees/TrainingProgramsModel.js
  models/products/CustomersModel.js
  models/products/OrdersModel.js
  models/products/PaymentOptionsModel.js
  models/products/ProductTypesModel.js
  models/products/ProductsModel.js
Labels: refactor
